=== jlokiec/PKCK-5/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:pkck = "pkck-zad2"
    targetNamespace = "pkck-zad2"
    elementFormDefault="qualified">
    <xs:element name = "document" type = "pkck:documentType">
        <!-- > unique studentID -->
        <xs:key name="unikNrStudentID">
            <xs:selector xpath="pkck:header/pkck:authors/pkck:author"/>
            <xs:field xpath="pkck:studentId"/>
        </xs:key>
		
		<!-- key for language -->
		<xs:key name="languageKey">
			<xs:selector xpath="pkck:languages/pkck:language"/>
			<xs:field xpath="@languageId"/>
		</xs:key>
	
		<!-- keyref to cd language -->
		<xs:keyref name="languageCd" refer="pkck:languageKey">
			<xs:selector xpath="pkck:catalog/pkck:cd/cdLanguage"/>
			<xs:field xpath="@languageId"/>
		</xs:keyref>
		
		<!-- key for genre -->
		<xs:key name="genreKey">
            <xs:selector xpath="pkck:genres/pkck:genre"/>
            <xs:field xpath="@genreId"/>
        </xs:key>
		
		<!-- keyref to cd genre -->
        <xs:keyref name="genreCd" refer="pkck:genreKey">
			<xs:selector xpath="pkck:catalog/pkck:cd/cdGenre"/>
			<xs:field xpath="@genreId"/>
		</xs:keyref>

        <!-- key for distributor -->
		<xs:key name="distributorKey">
            <xs:selector xpath="pkck:distributors/pkck:distributor"/>
            <xs:field xpath="@distributorId"/>
        </xs:key>
		
		<!-- keyref to cd distributor -->
        <xs:keyref name="distributorCd" refer="pkck:distributorKey">
			<xs:selector xpath="pkck:catalog/pkck:cd/cdDistributor"/>
			<xs:field xpath="@distributorId"/>
		</xs:keyref>

        <!-- key for musician -->
		<xs:key name="musicianKey">
            <xs:selector xpath="pkck:musicians/pkck:musician"/>
            <xs:field xpath="@musicianId"/>
        </xs:key>
		
		<!-- keyref to cd musician -->
        <xs:keyref name="musicianCd" refer="pkck:distributorKey">
			<xs:selector xpath="pkck:catalog/pkck:cd/cdMusician"/>
			<xs:field xpath="@musicianId"/>
		</xs:keyref>
    </xs:element>
    <!-- document type -->
    <xs:complexType name = "documentType">
        <xs:sequence>
            <xs:element name = "header" type = "pkck:headerType"/>
            <xs:element name = "musicians" type = "pkck:musiciansType"/>
            <xs:element name = "genres" type = "pkck:genresType"/>
            <xs:element name = "languages" type = "pkck:languagesType"/>
            <xs:element name = "distributors" type = "pkck:distributorsType"/>
            <xs:element name = "catalog" type = "pkck:catalogType"/>
        </xs:sequence>
    </xs:complexType>
	
    <!-- header type -->
    <xs:complexType name="headerType">
        <xs:sequence>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="author" type="pkck:authorType" maxOccurs="2"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name = "modificationDate" type = "xs:date"/>
            <xs:element name = "description" type = "xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="languagesType">
        <xs:sequence>
            <xs:element name = "language" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name = "languageId" type = "xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- author type -->
    <xs:complexType name = "authorType">
        <xs:sequence>
            <xs:group ref="pkck:osoba"/>
            <xs:element name = "studentId">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:group name = "osoba">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "surname" type = "xs:string"/>
        </xs:sequence>
    </xs:group>
    <!-- musicians type -->
    <xs:complexType name = "musiciansType">
        <xs:sequence>
            <xs:element name = "musician" type = "pkck:musicianType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- musician type -->
    <xs:complexType name = "musicianType">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "surname" type = "xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="musicianId" type="xs:string" use="required"/>
    </xs:complexType>
    <!-- genres type -->
    <xs:complexType name = "genresType">
        <xs:sequence>
            <xs:element name = "genre" type = "pkck:genreType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- genre type -->
    <xs:complexType name = "genreType">
        <xs:attribute name = "genreId" type = "xs:string"/>
        <xs:attribute name = "genreName" type = "xs:string"/>
    </xs:complexType>
    <!-- distributors type -->
    <xs:complexType name = "distributorsType">
        <xs:sequence>
            <xs:element name = "distributor" maxOccurs="unbounded">
                <xs:complexType >
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name = "distributorId" type = "xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- catalog type -->
    <xs:complexType name = "catalogType">
        <xs:sequence>
            <xs:element name = "cd" type = "pkck:cdType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- cd type -->
    <xs:complexType name = "cdType">
        <xs:sequence>
            <xs:element name = "cdMusician">
                <xs:complexType>
                    <xs:attribute name="musicianId" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name = "title" type = "xs:string"/>
            <xs:element name = "cdGenre">
                <xs:complexType>
                    <xs:attribute name="genreId" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name = "cdLanguage">
                <xs:complexType>
                    <xs:attribute name="languageId" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name = "premiereDate" type = "xs:string"/>
            <xs:element name = "numberOfCds" type = "xs:decimal"/>
            <xs:element name = "price">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name = "currency" type = "xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name = "cdDistributor">
                <xs:complexType>
                    <xs:attribute name="distributorId" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jlokiec/PKCK-5/resources/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<document 
xmlns ="pkck-zad2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="pkck-zad2 schema.xsd">
    <header>
        <authors>
            <author>
                <name>Maciej</name>
                <surname>Cierpikowski</surname>
                <studentId>210153</studentId>
            </author>
            <author>
                <name>Jakub</name>
                <surname>Łokieć</surname>
                <studentId>210259</studentId>
            </author>
        </authors>
        <modificationDate>2019-04-12</modificationDate>
        <description>Katalog płyt CD z muzyką</description>
    </header>

    <musicians>
        <musician musicianId="QUEEN">
            <name>Queen</name>
        </musician>
        <musician musicianId="CPLAY">
            <name>Coldplay</name>
        </musician>
        <musician musicianId="ARIZONA">
            <name>A R I Z O N A</name>
        </musician>
        <musician musicianId="BJOVI">
            <name>Bon Jovi</name>
        </musician>
        <musician musicianId="PFLOYD">
            <name>Pink Floyd</name>
        </musician>
        <musician musicianId="ACDC">
            <name>AC/DC</name>
        </musician>
        <musician musicianId="DPODSIADLO">
            <name>Dawid</name>
            <surname>Podsiadło</surname>
        </musician>
        <musician musicianId="KORTEZ">
            <name>Kortez</name>
        </musician>
        <musician musicianId="PROBLEM">
            <name>PRO8L3M</name>
        </musician>
        <musician musicianId="DZAWIALOW">
            <name>Daria</name>
            <surname>Zawiałow</surname>
        </musician>
        <musician musicianId="PDOMAGALA">
            <name>Paweł</name>
            <surname>Domagała</surname>
        </musician>
        <musician musicianId="TACO">
            <name>Taco Hemingway</name>
        </musician>
        <musician musicianId="KINGS">
            <name>Kings of Leon</name>
        </musician>
        <musician musicianId="SLAWOMIR">
            <name>Sławomir</name>
        </musician>
        <musician musicianId="WILKI">
            <name>Wilki</name>
        </musician>
        <musician musicianId="GITARY">
            <name>Elektryczne Gitary</name>
        </musician>
        <musician musicianId="KBEDNAREK">
            <name>Kamil</name>
            <surname>Bednarek</surname>
        </musician>
        <musician musicianId="STRACHY">
            <name>Strachy na Lachy</name>
        </musician>
    </musicians>

    <genres>
        <genre genreId="ROCK" genreName="rock"/>
        <genre genreId="SROCK" genreName="soft rock"/>
        <genre genreId="AROCK" genreName="rock alternatywny"/>
        <genre genreId="PROCK" genreName="rock progresywny"/>
        <genre genreId="HROCK" genreName="hard rock"/>
        <genre genreId="POP" genreName="pop"/>
        <genre genreId="RAP" genreName="rap"/>
        <genre genreId="DPOLO" genreName="disco polo"/>
        <genre genreId="REG" genreName="reggae"/>
    </genres>

    <languages>
        <language languageId="polski">polski</language>
        <language languageId="angielski">angielski</language>
    </languages>

    <distributors>
        <distributor distributorId="UMP">Universal Music Polska</distributor>
        <distributor distributorId="WMP">Warner Music Poland</distributor>
        <distributor distributorId="AR">Atlantic Records</distributor>
        <distributor distributorId="SME">Sony Music Entertainment</distributor>
        <distributor distributorId="FKO">Firma Księgarska Olesiejuk</distributor>
        <distributor distributorId="AGO">Agora S.A.</distributor>
        <distributor distributorId="MYS">Mystic Production</distributor>
        <distributor distributorId="ASF">Asfalt Distro</distributor>
        <distributor distributorId="EMU">e-Muzyka</distributor>
    </distributors>

    <catalog>
        <cd>
            <cdMusician musicianId="PFLOYD"/>
            <title>The Dark Side Of The Moon</title>
            <coverImg src="img/the-dark-side-of-the-moon.jpg"/>
            <cdGenre genreId="PROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>26.09.2011</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">31.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="QUEEN"/>
            <title>The Greatest Hits I, II &amp; III</title>
            <coverImg src="img/the-greatest-hits-i-ii-iii.jpg"/>
            <cdGenre genreId="ROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>24.06.2011</premiereDate>
            <numberOfCds>3</numberOfCds>
            <price currency="PLN">59.99</price>
            <cdDistributor distributorId="UMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="CPLAY"/>
            <title>A Head Full Of Dreams</title>
            <coverImg src="img/a-head-full-of-dreams.jpg"/>
            <cdGenre genreId="SROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>04.12.2015</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">46.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="CPLAY"/>
            <title>Ghost Stories</title>
            <coverImg src="img/ghost-stories.jpg"/>
            <cdGenre genreId="SROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>19.05.2014</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">34.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="CPLAY"/>
            <title>Parachutes</title>
            <coverImg src="img/parachutes.jpg"/>
            <cdGenre genreId="SROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>10.07.2000</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">24.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="CPLAY"/>
            <title>X &amp; Y</title>
            <coverImg src="img/x-y.jpg"/>
            <cdGenre genreId="SROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>06.06.2005</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">21.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="CPLAY"/>
            <title>Mylo Xyloto</title>
            <coverImg src="img/mylo-xyloto.jpg"/>
            <cdGenre genreId="SROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>24.10.2011</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">30.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="ARIZONA"/>
            <title>Gallery</title>
            <coverImg src="img/gallery.jpg"/>
            <cdGenre genreId="AROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>19.05.2017</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="USD">7.99</price>
            <cdDistributor distributorId="AR"/>
        </cd>
        <cd>
            <cdMusician musicianId="BJOVI"/>
            <title>This House Is Not For Sale</title>
            <coverImg src="img/this-house-is-not-for-sale.jpg"/>
            <cdGenre genreId="ROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>04.11.2016</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">39.99</price>
            <cdDistributor distributorId="UMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="PFLOYD"/>
            <title>The Wall</title>
            <coverImg src="img/the-wall.jpg"/>
            <cdGenre genreId="PROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>26.09.2011</premiereDate>
            <numberOfCds>2</numberOfCds>
            <price currency="PLN">40.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="PFLOYD"/>
            <title>The Division Bell</title>
            <coverImg src="img/the-division-bell.jpg"/>
            <cdGenre genreId="PROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>26.09.2011</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">31.99</price>
            <cdDistributor distributorId="WMP"/>
        </cd>
        <cd>
            <cdMusician musicianId="ACDC"/>
            <title>Black Ice</title>
            <coverImg src="img/black-ice.jpg"/>
            <cdGenre genreId="HROCK"/>
            <cdLanguage languageId="angielski"/>
            <premiereDate>20.10.2008</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">79.99</price>
            <cdDistributor distributorId="SME"/>
        </cd>
        <cd>
            <cdMusician musicianId="DPODSIADLO"/>
            <title>Małomiasteczkowy</title>
            <coverImg src="img/podsiadlo.jpg"/>
            <cdGenre genreId="POP"/>
            <cdLanguage languageId="polski"/>
            <premiereDate>19.10.2018</premiereDate>
            <numberOfCds>1</numberOfCds>
            <price currency="PLN">36.99</price>
            <cdDistributor distributorId="SME"/>
        </cd>
        <cd>
            <cdMusician musicianId="KORTEZ"/>
            <title>Mini dom</title>
            <coverImg src="img/kortez.jpg"/>
            <cdGenre genreId="POP"/>
            <cdLanguage languageId="polski"/>
